/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedIndicacoesRouteImport } from './routes/_authenticated/indicacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedSuporteRouteRouteImport } from './routes/_authenticated/suporte/route'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminIndicacoesRouteImport } from './routes/_authenticated/admin/indicacoes'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'
import { Route as AuthenticatedAdminSaquesRouteImport } from './routes/_authenticated/admin/saques'
import { Route as AuthenticatedAdminSuporteRouteRouteImport } from './routes/_authenticated/admin/suporte/route'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedSuporteIndexRouteImport } from './routes/_authenticated/suporte/index'
import { Route as AuthenticatedSuporteTicketIdRouteImport } from './routes/_authenticated/suporte/$ticketId'
import { Route as AuthenticatedAdminSuporteIndexRouteImport } from './routes/_authenticated/admin/suporte/index'
import { Route as AuthenticatedAdminSuporteTicketIdRouteImport } from './routes/_authenticated/admin/suporte/$ticketId'
import { Route as ApiPublicProductImageSplatRouteImport } from './routes/api/public/product-image/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicacoesRoute = AuthenticatedIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuporteRouteRoute =
  AuthenticatedSuporteRouteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIndicacoesRoute =
  AuthenticatedAdminIndicacoesRouteImport.update({
    id: '/indicacoes',
    path: '/indicacoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSaquesRoute =
  AuthenticatedAdminSaquesRouteImport.update({
    id: '/saques',
    path: '/saques',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSuporteRouteRoute =
  AuthenticatedAdminSuporteRouteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedSuporteIndexRoute =
  AuthenticatedSuporteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuporteRouteRoute,
  } as any)
const AuthenticatedSuporteTicketIdRoute =
  AuthenticatedSuporteTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedSuporteRouteRoute,
  } as any)
const AuthenticatedAdminSuporteIndexRoute =
  AuthenticatedAdminSuporteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSuporteRouteRoute,
  } as any)
const AuthenticatedAdminSuporteTicketIdRoute =
  AuthenticatedAdminSuporteTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedAdminSuporteRouteRoute,
  } as any)
const ApiPublicProductImageSplatRoute =
  ApiPublicProductImageSplatRouteImport.update({
    id: '/api/public/product-image/$',
    path: '/api/public/product-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/suporte': typeof AuthenticatedSuporteRouteRouteWithChildren
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteRouteRouteWithChildren
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/indicacoes': typeof AuthenticatedAdminIndicacoesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/suporte/$ticketId': typeof AuthenticatedSuporteTicketIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/suporte/': typeof AuthenticatedSuporteIndexRoute
  '/admin/suporte/$ticketId': typeof AuthenticatedAdminSuporteTicketIdRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/admin/suporte/': typeof AuthenticatedAdminSuporteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/indicacoes': typeof AuthenticatedAdminIndicacoesRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/suporte/$ticketId': typeof AuthenticatedSuporteTicketIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/suporte': typeof AuthenticatedSuporteIndexRoute
  '/admin/suporte/$ticketId': typeof AuthenticatedAdminSuporteTicketIdRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/suporte': typeof AuthenticatedSuporteRouteRouteWithChildren
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/indicacoes': typeof AuthenticatedIndicacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/suporte': typeof AuthenticatedAdminSuporteRouteRouteWithChildren
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/indicacoes': typeof AuthenticatedAdminIndicacoesRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/saques': typeof AuthenticatedAdminSaquesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/suporte/$ticketId': typeof AuthenticatedSuporteTicketIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/suporte/': typeof AuthenticatedSuporteIndexRoute
  '/_authenticated/admin/suporte/$ticketId': typeof AuthenticatedAdminSuporteTicketIdRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
  '/_authenticated/admin/suporte/': typeof AuthenticatedAdminSuporteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/admin'
    | '/suporte'
    | '/carteira'
    | '/indicacoes'
    | '/perfil'
    | '/produto/$slug'
    | '/admin/suporte'
    | '/admin/configuracoes'
    | '/admin/indicacoes'
    | '/admin/produtos'
    | '/admin/saques'
    | '/admin/usuarios'
    | '/suporte/$ticketId'
    | '/admin/'
    | '/suporte/'
    | '/admin/suporte/$ticketId'
    | '/api/public/product-image/$'
    | '/admin/suporte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/carteira'
    | '/indicacoes'
    | '/perfil'
    | '/produto/$slug'
    | '/admin/configuracoes'
    | '/admin/indicacoes'
    | '/admin/produtos'
    | '/admin/saques'
    | '/admin/usuarios'
    | '/suporte/$ticketId'
    | '/admin'
    | '/suporte'
    | '/admin/suporte/$ticketId'
    | '/api/public/product-image/$'
    | '/admin/suporte'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/suporte'
    | '/_authenticated/carteira'
    | '/_authenticated/indicacoes'
    | '/_authenticated/perfil'
    | '/produto/$slug'
    | '/_authenticated/admin/suporte'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/indicacoes'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/saques'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/suporte/$ticketId'
    | '/_authenticated/admin/'
    | '/_authenticated/suporte/'
    | '/_authenticated/admin/suporte/$ticketId'
    | '/api/public/product-image/$'
    | '/_authenticated/admin/suporte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicProductImageSplatRoute: typeof ApiPublicProductImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicacoes': {
      id: '/_authenticated/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AuthenticatedIndicacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/indicacoes': {
      id: '/_authenticated/admin/indicacoes'
      path: '/indicacoes'
      fullPath: '/admin/indicacoes'
      preLoaderRoute: typeof AuthenticatedAdminIndicacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/saques': {
      id: '/_authenticated/admin/saques'
      path: '/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof AuthenticatedAdminSaquesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/suporte': {
      id: '/_authenticated/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AuthenticatedAdminSuporteRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/suporte/': {
      id: '/_authenticated/suporte/'
      path: '/'
      fullPath: '/suporte/'
      preLoaderRoute: typeof AuthenticatedSuporteIndexRouteImport
      parentRoute: typeof AuthenticatedSuporteRouteRoute
    }
    '/_authenticated/suporte/$ticketId': {
      id: '/_authenticated/suporte/$ticketId'
      path: '/$ticketId'
      fullPath: '/suporte/$ticketId'
      preLoaderRoute: typeof AuthenticatedSuporteTicketIdRouteImport
      parentRoute: typeof AuthenticatedSuporteRouteRoute
    }
    '/_authenticated/admin/suporte/': {
      id: '/_authenticated/admin/suporte/'
      path: '/'
      fullPath: '/admin/suporte/'
      preLoaderRoute: typeof AuthenticatedAdminSuporteIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSuporteRouteRoute
    }
    '/_authenticated/admin/suporte/$ticketId': {
      id: '/_authenticated/admin/suporte/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/suporte/$ticketId'
      preLoaderRoute: typeof AuthenticatedAdminSuporteTicketIdRouteImport
      parentRoute: typeof AuthenticatedAdminSuporteRouteRoute
    }
    '/api/public/product-image/$': {
      id: '/api/public/product-image/$'
      path: '/api/public/product-image/$'
      fullPath: '/api/public/product-image/$'
      preLoaderRoute: typeof ApiPublicProductImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminSuporteRouteRouteChildren {
  AuthenticatedAdminSuporteTicketIdRoute: typeof AuthenticatedAdminSuporteTicketIdRoute
  AuthenticatedAdminSuporteIndexRoute: typeof AuthenticatedAdminSuporteIndexRoute
}

const AuthenticatedAdminSuporteRouteRouteChildren: AuthenticatedAdminSuporteRouteRouteChildren =
  {
    AuthenticatedAdminSuporteTicketIdRoute:
      AuthenticatedAdminSuporteTicketIdRoute,
    AuthenticatedAdminSuporteIndexRoute: AuthenticatedAdminSuporteIndexRoute,
  }

const AuthenticatedAdminSuporteRouteRouteWithChildren =
  AuthenticatedAdminSuporteRouteRoute._addFileChildren(
    AuthenticatedAdminSuporteRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSuporteRouteRoute: typeof AuthenticatedAdminSuporteRouteRouteWithChildren
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminIndicacoesRoute: typeof AuthenticatedAdminIndicacoesRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminSaquesRoute: typeof AuthenticatedAdminSaquesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSuporteRouteRoute:
      AuthenticatedAdminSuporteRouteRouteWithChildren,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminIndicacoesRoute: AuthenticatedAdminIndicacoesRoute,
    AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
    AuthenticatedAdminSaquesRoute: AuthenticatedAdminSaquesRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSuporteRouteRouteChildren {
  AuthenticatedSuporteTicketIdRoute: typeof AuthenticatedSuporteTicketIdRoute
  AuthenticatedSuporteIndexRoute: typeof AuthenticatedSuporteIndexRoute
}

const AuthenticatedSuporteRouteRouteChildren: AuthenticatedSuporteRouteRouteChildren =
  {
    AuthenticatedSuporteTicketIdRoute: AuthenticatedSuporteTicketIdRoute,
    AuthenticatedSuporteIndexRoute: AuthenticatedSuporteIndexRoute,
  }

const AuthenticatedSuporteRouteRouteWithChildren =
  AuthenticatedSuporteRouteRoute._addFileChildren(
    AuthenticatedSuporteRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSuporteRouteRoute: typeof AuthenticatedSuporteRouteRouteWithChildren
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedIndicacoesRoute: typeof AuthenticatedIndicacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSuporteRouteRoute: AuthenticatedSuporteRouteRouteWithChildren,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedIndicacoesRoute: AuthenticatedIndicacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicProductImageSplatRoute: ApiPublicProductImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
